spring.application.name=Book_My_Show

server.servlet.context-path=/book-my-show

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.test.uri=mongodb://localhost:27017/test
spring.data.mongodb.test2.uri=mongodb://localhost:27017/test2

spring.data.elasticsearch.cluster-nodes=localhost:9200
spring.data.elasticsearch.cluster-name=elastic

spring.cache.type=redis
spring.cache.host=localhost
spring.cache.port=6379

